version: 2
jobs:
  "lts-12.16":
    docker:
      - image: fpco/stack-build:lts-12.16
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - lts1216-website-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - lts1216-website-v1-
      - run: stack setup
      - run: stack build hlint
      - save_cache:
          key: lts1216-website-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
      - run: stack exec -- hlint src/ test/
      - run: stack build --test --copy-bins
      - store_artifacts:
          path: ~/.local/bin/website
          destination: website

workflows:
  version: 2
  build:
    jobs:
      - "lts-12.16"