version: 2
jobs:
  "lts-12.16":
    docker:
      - image: fpco/stack-build:lts-12.16
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: homestead
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: website
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - lts1216-website-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - lts1216-website-v1-
      - run: stack setup
      - run: stack build hlint
      - run: stack exec -- hlint src/ test/
      - run:
          name: Test and Install
          command: stack build --test --copy-bins
          environment:
            YESOD_PGHOST: localhost
      - save_cache:
          key: lts1216-website-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
      - store_artifacts:
          path: ~/.local/bin/website
          destination: website

workflows:
  version: 2
  build:
    jobs:
      - "lts-12.16"