apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "website.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "website.name" . }}
    helm.sh/chart: {{ include "website.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  admin-email: {{ .Values.admin.email | b64enc | quote }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
  postgres-username: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  postgres-database: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}