apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "website.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "website.name" . }}
    helm.sh/chart: {{ include "website.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.admin.email | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  YESOD_PGUSER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  YESOD_PGPASS: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  YESOD_PGDATABASE: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}